spring.application.name=whitelbl
server.port=8082

# Database configuration
#spring.datasource.url=jdbc:mysql://weppay.cbaq4o488bzr.ap-south-1.rds.amazonaws.com/wepPay?createDatabaseIfNotExist=true
#spring.datasource.username=admin
#spring.datasource.password=Bachar!2025
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#  Database configuration(local)
spring.datasource.url=jdbc:mysql://localhost:3306/myproject?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://weppay.cbaq4o488bzr.ap-south-1.rds.amazonaws.com/wepPay?createDatabaseIfNotExist=true
#spring.datasource.username=admin
#spring.datasource.password=Bachar!2025
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.forward-headers-strategy=framework

trexo.key=8f1ae4545787fa1ccbd784a58aa22fb4
trexo.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOjE2OSwiYXBpX2tleSI6IjhmMWFlNDU0NTc4N2ZhMWNjYmQ3ODRhNThhYTIyZmI0IiwiYWNjZXNzX3Rva2VuIjoiM2ExY2ZkZmNhOTcxMWE1M2FiZDI0OTYyN2VjNTQ1ZmJkMmU4MGI0OWJlNWQxNmYxMjhlNmQ1YTZkMzMxMjYzZCIsImVudmlyb25tZW50IjoicHJvZHVjdGlvbiIsImlhdCI6MTc2MzE0MjQ2NH0.On73KHL7uyYcTm7XMVx_B-y6Q1i_3ydapgQOhF6LH14



# Hibernate/JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Only for development - shows SQL parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


logging.level.org.hibernate.SQL=DEBUG

# JWT Configuration
jwt.secret=b7d93f6f0a0f2d6b48ac7c3b5b9de01fd2f4a7c682bc991b88e65d9f1d293aa1
jwt.expiration=86400000
